logging:
  level:
    root: INFO
    org.springframework: INFO
    com.mgu.mlnba.security: DEBUG
    
spring:
  data:
    mongodb:
      uri: mongodb://mlnba:mlnba@localhost/mlnba
---
spring.profiles: gke
spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER}:${MONGODB_USER_PASSWORD}@${MONGODB_HOST}/${MONGODB_BASE}
