logging:
  level:
    root: INFO
    org.springframework: INFO
    com.mgu.mlnba.security: DEBUG
    
#spring:
#    datasource:
#        url: jdbc:postgresql://localhost/mlnba
#        username: mlnba
#        password: mlnba
#        driver-class-name: org.postgresql.Driver
#        
#    jpa:
#        show-sql: true
#        properties:
#            hibernate:
#                temp:
#                    use_jdbc_metadata_defaults: false # to suppress an annoying exception that occurs when JPA (Hibernate) tries to verify PostgreSQL CLOB feature.
#spring:
#  data:
#    mongodb:
#      uri: mongodb://mlnba:mlnba@localhost/mlnba
spring:
  data:
    mongodb:
      uri: mongodb://Mlnba:${MANGOPASSWORD}@mlnba-mango-cluster-ip-service/admin
---
spring.profiles: gke
spring:
    datasource:
        url: jdbc:postgresql://mlnba-mango-cluster-ip-service/mlnba
        username: root
        password: ${mangopassword}
        driver-class-name: org.postgresql.Driver
        
    jpa:
        show-sql: true
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false # to suppress an annoying exception that occurs when JPA (Hibernate) tries to verify PostgreSQL CLOB feature.
#spring:
#  data:
#    mongodb:
#      uri: mongodb://root:${MANGOPASSWORD}@mlnba-mango-cluster-ip-service/mlnba