  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'mlnba-backend-deployment'
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mlnba-backend
  template:
    metadata:
      labels:
        component: mlnba-backend
    spec:
        containers:
          - name: mlnba-api
            image: marc06210/mlnba-backend
            ports:
              - containerPort: 8080
            env: 
              - name: MONGODB_HOST
                value: mlnba-mongo-cluster-ip-service        
              - name: MONGODB_BASE
                value: mlnba
              - name: MONGODB_USER
                value: mlnbauser
              - name: MONGODB_USER_PASSWORD
                valueFrom: 
                  secretKeyRef:
                    name: mango-user-password
                    key:  MONGOUSERPASSWORD
